{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/sandia-hand.json"}, "html": {"href": "#!/osrf/sandia-hand"}, "avatar": {"href": "data/bytebucket.org/ravatar/{ffa260f4-e54c-4b4b-ab64-4d0fc5a90091}ts=default"}}, "type": "repository", "name": "sandia-hand", "full_name": "osrf/sandia-hand", "uuid": "{ffa260f4-e54c-4b4b-ab64-4d0fc5a90091}"}, "links": {"attachments": {"href": "data/repositories/osrf/sandia-hand/issues/6/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/sandia-hand/issues/6.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/sandia-hand/issues/6/watch"}, "comments": {"href": "data/repositories/osrf/sandia-hand/issues/6/comments_page=1.json"}, "html": {"href": "#!/osrf/sandia-hand/issues/6/latest-sandia-hand-from-default-branch"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/sandia-hand/issues/6/vote"}}, "reporter": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "title": "Latest Sandia Hand from default branch breaks drcsim", "component": null, "votes": 0, "watches": 1, "content": {"raw": "When trying to compile default drcsim using latest sandia-hand, the compilation seems to broken with the next message:\r\n\r\n```\r\n[ 72%] Generating irobot_hand_description.urdf\r\nLinking CXX shared library libDRCVehiclePlugin.so\r\n[ 72%] Built target DRCVehiclePlugin\r\nTraceback (most recent call last):\r\n  File \"/opt/ros/fuerte/stacks/xacro/xacro.py\", line 35, in <module>\r\n    xacro.main()\r\n  File \"/opt/ros/fuerte/stacks/xacro/src/xacro.py\", line 563, in main\r\n    eval_self_contained(doc)\r\n  File \"/opt/ros/fuerte/stacks/xacro/src/xacro.py\", line 504, in eval_self_contained\r\n    eval_all(doc.documentElement, macros, symbols)\r\n  File \"/opt/ros/fuerte/stacks/xacro/src/xacro.py\", line 456, in eval_all\r\n    str(node.tagName))\r\nxacro.XacroException: Some parameters were not set for macro xacro:sandia_hand\r\n```\r\n\r\nI saw this error in today's [nightly build](http://build.osrfoundation.org/job/drcsim-debbuild/214/consoleFull) and was able to reproduce it locally. Using latest stable sandia-hand_5.1.13-1 works just fine.\r\n\r\nP.D: I will update jenkins to launch drcsim after sandia-hand default changes to be able to catch this kind of errors as soon as possible.", "markup": "markdown", "html": "<p>When trying to compile default drcsim using latest sandia-hand, the compilation seems to broken with the next message:</p>\n<div class=\"codehilite\"><pre><span></span>[ 72%] Generating irobot_hand_description.urdf\nLinking CXX shared library libDRCVehiclePlugin.so\n[ 72%] Built target DRCVehiclePlugin\nTraceback (most recent call last):\n  File &quot;/opt/ros/fuerte/stacks/xacro/xacro.py&quot;, line 35, in &lt;module&gt;\n    xacro.main()\n  File &quot;/opt/ros/fuerte/stacks/xacro/src/xacro.py&quot;, line 563, in main\n    eval_self_contained(doc)\n  File &quot;/opt/ros/fuerte/stacks/xacro/src/xacro.py&quot;, line 504, in eval_self_contained\n    eval_all(doc.documentElement, macros, symbols)\n  File &quot;/opt/ros/fuerte/stacks/xacro/src/xacro.py&quot;, line 456, in eval_all\n    str(node.tagName))\nxacro.XacroException: Some parameters were not set for macro xacro:sandia_hand\n</pre></div>\n\n\n<p>I saw this error in today's <a data-is-external-link=\"true\" href=\"http://build.osrfoundation.org/job/drcsim-debbuild/214/consoleFull\" rel=\"nofollow\">nightly build</a> and was able to reproduce it locally. Using latest stable sandia-hand_5.1.13-1 works just fine.</p>\n<p>P.D: I will update jenkins to launch drcsim after sandia-hand default changes to be able to catch this kind of errors as soon as possible.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2013-04-15T14:56:41.354809+00:00", "milestone": null, "updated_on": "2013-04-17T17:00:14.363946+00:00", "type": "issue", "id": 6}