{"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/455/comments/15157270.json"}, "html": {"href": "#!/osrf/drcsim/issues/455#comment-15157270"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/455.json"}}, "type": "issue", "id": 455, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "can't spawn multiple atlases"}, "content": {"raw": "Is the protocol to close this issue after Gazebo 4.1 gets patched?", "markup": "markdown", "html": "<p>Is the protocol to close this issue after Gazebo 4.1 gets patched?</p>", "type": "rendered"}, "created_on": "2015-01-26T19:24:41.532824+00:00", "user": {"display_name": "Jackie K", "uuid": "{e3d60b62-b7c7-4863-b9b9-cdae9f123cec}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be3d60b62-b7c7-4863-b9b9-cdae9f123cec%7D"}, "html": {"href": "https://bitbucket.org/%7Be3d60b62-b7c7-4863-b9b9-cdae9f123cec%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/ea011fa2919d4bd4568b32b440eda779d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJK-0.png"}}, "nickname": "jacquelinekay", "type": "user", "account_id": "557058:f56c822f-f75c-4665-80f9-6e7764893b9c"}, "updated_on": null, "type": "issue_comment", "id": 15157270}