{"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2343427.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2343427"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "I reinstalled the drcsim and gazebo package on my local machine and it works if I use localhost as the ROS_IP (although the error is not the same) .... \n\nNext: checking for networking problems on a new cloud instance.", "markup": "markdown", "html": "<p>I reinstalled the drcsim and gazebo package on my local machine and it works if I use localhost as the ROS_IP (although the error is not the same) .... </p>\n<p>Next: checking for networking problems on a new cloud instance.</p>", "type": "rendered"}, "created_on": "2012-11-08T18:11:42.179667+00:00", "user": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "updated_on": null, "type": "issue_comment", "id": 2343427}