{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "links": {"attachments": {"href": "data/repositories/osrf/drcsim/issues/227/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/drcsim/issues/227.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/drcsim/issues/227/watch"}, "comments": {"href": "data/repositories/osrf/drcsim/issues/227/comments_page=1.json"}, "html": {"href": "#!/osrf/drcsim/issues/227/quadprogpp-required-to-link"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/drcsim/issues/227/vote"}}, "reporter": null, "title": "QuadProgPP required to link actionlib_server", "component": null, "votes": 0, "watches": 3, "content": {"raw": "I am installing drcsim 2.5 in a 64-bit Ubuntu machine (12.10) with Ros Groovy. I get the following error:\r\n\r\n/home/ana/Software/drcsim/ros/atlas_msgs/../../plugins/AtlasSimInterface_1.0.8/lib64/libAtlasSimInterface.so: error: undefined reference to 'QuadProgPP::solve_quadprog_chol_lukewarmstart(bool, QuadProgPP::Matrix<double>&, QuadProgPP::Vector<double>&, QuadProgPP::Vector<double> const&, QuadProgPP::Matrix<double> const&, QuadProgPP::Vector<double> const&, QuadProgPP::Vector<double>&, int, int, double, QuadProgPP::Matrix<double> const&, QuadProgPP::Vector<double> const&, QuadProgPP::Vector<double> const*, QuadProgPP::Vector<double> const*, QuadProgPP::Vector<double> const*, QuadProgPP::Vector<double> const*)'\r\n/home/ana/Software/drcsim/ros/atlas_msgs/../../plugins/AtlasSimInterface_1.0.8/lib64/libAtlasSimInterface.so: error: undefined reference to 'QuadProgPP::solve_quadprog(QuadProgPP::Matrix<double>&, QuadProgPP::Vector<double>&, QuadProgPP::Matrix<double> const&, QuadProgPP::Vector<double> const&, QuadProgPP::Matrix<double> const&, QuadProgPP::Vector<double> const&, QuadProgPP::Vector<double>&)'\r\n/home/ana/Software/drcsim/ros/atlas_msgs/../../plugins/AtlasSimInterface_1.0.8/lib64/libAtlasSimInterface.so: error: undefined reference to 'QuadProgPP::solve_quadprog_chol_init(bool, QuadProgPP::Matrix<double>&, QuadProgPP::Vector<double>&, QuadProgPP::Matrix<double> const&, QuadProgPP::Vector<double> const&, QuadProgPP::Matrix<double> const&, QuadProgPP::Vector<double> const&, QuadProgPP::Vector<double>&, int&, int&, double&, QuadProgPP::Matrix<double>&, QuadProgPP::Vector<double>&, QuadProgPP::Vector<double>*, QuadProgPP::Vector<double>*, QuadProgPP::Vector<double>*, QuadProgPP::Vector<double>*)'\r\n \r\n\r\nI got some other errors that were fixed by adding rt, qpOASES and z to the target_link_libraries, but the error related QuadProgPP persists. Any advice would be highly appreciated.", "markup": "markdown", "html": "<p>I am installing drcsim 2.5 in a 64-bit Ubuntu machine (12.10) with Ros Groovy. I get the following error:</p>\n<p>/home/ana/Software/drcsim/ros/atlas_msgs/../../plugins/AtlasSimInterface_1.0.8/lib64/libAtlasSimInterface.so: error: undefined reference to 'QuadProgPP::solve_quadprog_chol_lukewarmstart(bool, QuadProgPP::Matrix&lt;double&gt;&amp;, QuadProgPP::Vector&lt;double&gt;&amp;, QuadProgPP::Vector&lt;double&gt; const&amp;, QuadProgPP::Matrix&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt;&amp;, int, int, double, QuadProgPP::Matrix&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt; const<em>, QuadProgPP::Vector&lt;double&gt; const</em>, QuadProgPP::Vector&lt;double&gt; const<em>, QuadProgPP::Vector&lt;double&gt; const</em>)'\n/home/ana/Software/drcsim/ros/atlas_msgs/../../plugins/AtlasSimInterface_1.0.8/lib64/libAtlasSimInterface.so: error: undefined reference to 'QuadProgPP::solve_quadprog(QuadProgPP::Matrix&lt;double&gt;&amp;, QuadProgPP::Vector&lt;double&gt;&amp;, QuadProgPP::Matrix&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt; const&amp;, QuadProgPP::Matrix&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt;&amp;)'\n/home/ana/Software/drcsim/ros/atlas_msgs/../../plugins/AtlasSimInterface_1.0.8/lib64/libAtlasSimInterface.so: error: undefined reference to 'QuadProgPP::solve_quadprog_chol_init(bool, QuadProgPP::Matrix&lt;double&gt;&amp;, QuadProgPP::Vector&lt;double&gt;&amp;, QuadProgPP::Matrix&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt; const&amp;, QuadProgPP::Matrix&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt; const&amp;, QuadProgPP::Vector&lt;double&gt;&amp;, int&amp;, int&amp;, double&amp;, QuadProgPP::Matrix&lt;double&gt;&amp;, QuadProgPP::Vector&lt;double&gt;&amp;, QuadProgPP::Vector&lt;double&gt;<em>, QuadProgPP::Vector&lt;double&gt;</em>, QuadProgPP::Vector&lt;double&gt;<em>, QuadProgPP::Vector&lt;double&gt;</em>)'</p>\n<p>I got some other errors that were fixed by adding rt, qpOASES and z to the target_link_libraries, but the error related QuadProgPP persists. Any advice would be highly appreciated.</p>", "type": "rendered"}, "assignee": null, "state": "wontfix", "version": null, "edited_on": null, "created_on": "2013-04-29T02:18:13.386703+00:00", "milestone": null, "updated_on": "2013-07-09T02:05:19.240424+00:00", "type": "issue", "id": 227}